[package]
name = "timed-dashmap"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dashmap = "^4"
tokio = { version = "^1", features = ["rt", "time", "macros", "test-util"] }